"""add profile fields to users

Revision ID: 45c48e506135
Revises: 6c41a0f7a915
Create Date: 2026-07-25 17:07:24.771227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45c48e506135'
down_revision: Union[str, Sequence[str], None] = '6c41a0f7a915'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('display_name', sa.String(), nullable=True))
    # server_default so this is safe even if existing rows already exist.
    op.add_column(
        'users', sa.Column('target_language', sa.String(), nullable=False, server_default='fr-FR')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'target_language')
    op.drop_column('users', 'display_name')
    # ### end Alembic commands ###
